name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1 
          aws-access-key-id: ${{secrets.S3_KEYS}}
          aws-secret-access-key: ${{secrets.S3_PASS}}
      - name: pushing to S3
        run: aws s3 sync ./build/. s3://fitness4me.online
