name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{secrets.S3_KEY}}
          aws-secret-access-key: ${{secrets.S3_PASSKEY}}

      # - name: Pushing to S3
      #   run: |
      #     aws s3 sync . "s3://fitness4me.online" --exclude ".git/*" --exclude ".github/*"
      - name: Delete from S3
        run: aws s3 rm s3://fitness4me.online/ --recursive

